### ISSUE TITLE
Clear All 

### ISSUE THREAD

**Issue by SnorlaxUsedGit** [MTACS/Lynx#281]
Its always so frustrating to swipe up all those apps in the app switcher to close them. It would be nice to have a “clear all” button or a “clear” button to get rid of all of those in the app switcher whether you’re on grid style or not.

**Comment by MTACS** [comment]
I already have this implemented, look under Lynx > App Switcher > 3D Touch to kill, and you can choose whether to have a confirmation or not. A button would be better but since the grid switcher on iPads and phones with it force enabled, has a completely different layout. 3D Touching to kill works in both the regular switcher and grid style without having to add any layouts
