### ISSUE TITLE
Lockscreen bugs

### ISSUE THREAD

**Issue by johnzaro** [MTACS/Lynx#9]
**Describe the bug**
1) "Hide swipe up" does not work
2) "disable camera swipe" + "force enable camera" does not work
the settings mentioned above are enabled however the "swipe up to unlock" text pops up and also I cannot open camera by pressing the camera button. 

**To Reproduce**
---

**Expected behavior**
---

**Screenshots**
---

**iDevice Information (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.3
 - Package Manager used to install Lynx: Zebra
 - Lynx Version (Can be found at the bottom of Settings pane): 1.0.7

**Additional context**
---

**Comment by MTACS** [comment]
The hide swipe up to unlock will be fixed in the next version, I completely rewrote what hides it. iOS disables the camera button when the swipe gesture is disabled, force enabling it only reenables the view of the button, not the actual functionality, I'll see if I can override the action to still open the camera manually, but since its done via an iOS policy aggregator, I'm not sure if my tweak will be able to overpower it
